server:
  port: 8080 # Boot stays on 8080
  shutdown: graceful
  tomcat:
    connection-timeout: 20000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nexus_connect
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  lifecycle:
    timeout-per-shutdown-phase: 30s
  sql:
    init:
      mode: never

jwt:
  secret: ${JWT_SECRET:change-me-please-change-me-please-change-me}
  expiration: ${JWT_EXPIRATION_MS:3600000}

nexus:
  nio:
    port: 8081
